apiVersion: batch/v1
kind: Job
metadata:
  name: download-images
spec:
  backoffLimit: 0
  completions: 8
  parallelism: 8
  template:
    spec:
      containers:
      - name: image-downloader
        image: hotohoto/minidalle2:0.1.3-cpu
        args: ["sh", "-c", ". ~/.poetry/env; poetry run poe download_images"]
        volumeMounts:
        - name: vol
          mountPath: /home/worker/minidalle2/datasets
        resources:
          requests:
            cpu: "500m"
            memory: 512Mi
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: minidalle2-nfs-pvc
