apiVersion: batch/v1
kind: Job
metadata:
  name: download-images
spec:
  backoffLimit: 0
  completions: 5  # FIXME
  parallelism: 5  # FIXME
  template:
    spec:
      containers:
      - name: image-downloader
        image: hotohoto/minidalle2:0.1.1-cpu
        # args: ["~/.poetry/bin/poetry", "run", "poe", "download_images"]
        volumeMounts:
        - name: vol
          mountPath: /home/worker/minidalle2/datasets
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: pvc-minidalle2-datasets-rwx
      securityContext:
        fsGroup: 1000  # mount volumes with the group ID set
