apiVersion: v1
kind: Pod
metadata:
  name: console
spec:
  containers:
  - image: hotohoto/minidalle2:0.1.1-cpu
    name: console
    volumeMounts:
    - name: vol
      mountPath: /home/worker/minidalle2/datasets
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc-minidalle2-datasets-rwx
  securityContext:
    fsGroup: 1000  # mount volumes with the group ID set
