apiVersion: v1
kind: Pod
metadata:
  name: minidalle2-idle
spec:
  containers:
  - image: hotohoto/minidalle2:0.1.3-cpu
    name: minidalle2-idle-container
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: vol
      mountPath: /home/worker/minidalle2/datasets
    resources:
      limits:
        cpu: 900m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    # we may need to run dmesg for NFS debugging
    # securityContext:
    #   privileged: true
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: minidalle2-nfs-pvc
