apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-volumes
spec:
  containers:
  - image: busybox
    name: busybox
    args: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: vol
      mountPath: /data
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: minidalle2-nfs-pvc
