apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minidalle2-datasets-rwo
spec:
  storageClassName: premium-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
